name: CI Backend

on:
  pull_request:
    branches: ["main", "dev"]

permissions:
  contents: read
  checks: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Seoul'
    steps:
      - uses: actions/checkout@v3

      - name: Check the timezone
        run: date

      - name: 자바 버전 17 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: test 경로 application.yml 파일 생성
        run: |
          mkdir -p ./src/test/resources
          echo "${{ secrets.TEST_APPLICATION_YML }}" > ./src/test/resources/application.yml

      - name: gradle 권한 부여
        run: chmod +x ./gradlew
        shell: bash

      - name: 빌드 시 캐시 적용
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: 빌드
        run: ./gradlew build

      - name: Jacoco 테스트 결과 출력
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          title: Code Coverage
          paths: ${{ github.workspace }}/**/build/reports/jacocoReport/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 60
          min-coverage-changed-files: 60
          update-comment: true

      - name: 테스트 결과 PR 코멘트에 등록
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: '**/build/test-results/test/TEST-*.xml'

      - name: 테스트 실패시 코드 라인에 대한 체크 추가
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.html'